# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'P2PLending' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for P2PLending
    pod 'Firebase/Core'
    pod 'Firebase/Database', '~> 5.3.0'
    pod 'Firebase/Messaging', '~> 5.3.0'

  # target 'P2PLending-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'P2PLendingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'P2PLending-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for P2PLending-tvOS

  target 'P2PLending-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
